# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    env:
     GOPATH: ${{ github.workspace }}/gopath
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up workspace
        working-directory: ./app
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'
      - name: setup gob
        run: go install github.com/kcmvp/gob@latest

      - name: Test with gob
        run: gob test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
